{
 "title": "Kubernetes JMX Dashboard",
 "description": "JMX Dashboard for Kubernetes Monitoring with Prometheus",
 "tags": [
  "jvm",
  "jmx",
  "prometheus",
  "prometheus-operator",
  "kubernetes"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "pod",
    "label": "Pod",
    "query": "label_values(up{job='jmx-exporter'}, pod)"
   }
  ]
 },
 "panels": [
  {
   "title": "Status",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "up{job='jmx-exporter',pod=\"$pod\"}"
    }
   ]
  },
  {
   "title": "Total CPU Cores",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 2, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "kube_pod_container_resource_limits_cpu_cores{job='kube-state-metrics',container='tomcat',pod=\"$pod\"}"
    }
   ]
  },
  {
   "title": "Total Memory",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 6, "y": 0 },
   "format": "decbytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "kube_pod_container_resource_limits_memory_bytes{job='kube-state-metrics',container='tomcat',pod=\"$pod\"}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 10, "y": 0 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{job='jmx-exporter',pod=\"$pod\"}"
    }
   ]
  },
  {
   "title": "Start Time",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 14, "y": 0 },
   "format": "dateTimeAsIso",
   "valueName": "avg",
   "targets": [
    {
     "expr": "process_start_time_seconds{job='jmx-exporter',pod=\"$pod\"}*1000"
    }
   ]
  },
  {
   "title": "JVM Version",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "expr": "label_join(jvm_info{pod=\"$pod\"}, \"jdk\", \", \", \"vendor\", \"runtime\", \"version\")"
    }
   ]
  },
  {
   "title": "CPU Usage [3m]",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 4 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(rate(container_cpu_usage_seconds_total{container=\"tomcat\",pod=\"$pod\"}[3m]))/avg(kube_pod_container_resource_limits_cpu_cores{container=\"tomcat\",pod=\"$pod\"})*100"
    }
   ]
  },
  {
   "title": "CPU Usage Timeline [3m]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 4, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{container=\"tomcat\",pod=\"$pod\"}[3m])",
     "legendFormat": "Usage"
    },
    {
     "expr": "rate(container_cpu_system_seconds_total{container=\"tomcat\",pod=\"$pod\"}[3m])",
     "legendFormat": "System"
    },
    {
     "expr": "rate(container_cpu_user_seconds_total{container=\"tomcat\",pod=\"$pod\"}[3m])",
     "legendFormat": "User"
    },
    {
     "expr": "avg(rate(container_cpu_usage_seconds_total{container=\"tomcat\",pod=\"$pod\"}[3m]))/avg(kube_pod_container_resource_limits_cpu_cores{container=\"tomcat\",pod=\"$pod\"})",
     "legendFormat": "Usage %"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 4 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(container_memory_usage_bytes{container=\"tomcat\",pod=\"$pod\"})/avg(kube_pod_container_resource_limits_memory_bytes{container=\"tomcat\",pod=\"$pod\"})*100"
    }
   ]
  },
  {
   "title": "Memory Usage Timeline",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 4 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_usage_bytes{container=\"tomcat\",pod=\"$pod\"}",
     "legendFormat": "Usage"
    },
    {
     "expr": "avg(container_memory_usage_bytes{container=\"tomcat\",pod=\"$pod\"})/avg(kube_pod_container_resource_limits_memory_bytes{container=\"tomcat\",pod=\"$pod\"})",
     "legendFormat": "Usage %"
    }
   ]
  },
  {
   "title": "JVM Memory Area (Heap)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{area=\"heap\",pod=\"$pod\"}",
     "legendFormat": "Used"
    },
    {
     "expr": " jvm_memory_bytes_committed{area=\"heap\",pod=\"$pod\"}",
     "legendFormat": "Committed"
    },
    {
     "expr": " jvm_memory_bytes_max{area=\"heap\",pod=\"$pod\"}",
     "legendFormat": "Max"
    },
    {
     "expr": "jvm_memory_bytes_used{area=\"heap\",pod=\"$pod\"}/jvm_memory_bytes_max{area=\"heap\",pod=\"$pod\"}",
     "legendFormat": "Usage %"
    }
   ]
  },
  {
   "title": "JVM Memory Area (Non-Heap)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 11 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{area=\"nonheap\",pod=\"$pod\"}",
     "legendFormat": "Used"
    },
    {
     "expr": " jvm_memory_bytes_committed{area=\"heap\",pod=\"$pod\"}",
     "legendFormat": "Committed"
    }
   ]
  },
  {
   "title": "JVM Memory Pool",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 11 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_used{pod=\"$pod\"}",
     "legendFormat": "{{pool}}"
    }
   ]
  },
  {
   "title": "JVM Threads used",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_current{pod=\"$pod\"}",
     "legendFormat": "Current"
    },
    {
     "expr": " jvm_threads_daemon{pod=\"$pod\"}",
     "legendFormat": "Daemon"
    },
    {
     "expr": " jvm_threads_peak{pod=\"$pod\"}",
     "legendFormat": "Peak"
    },
    {
     "expr": " jvm_threads_deadlocked{pod=\"$pod\"}",
     "legendFormat": "Deadlocked"
    }
   ]
  },
  {
   "title": "JVM Class Loading",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_classes_loaded{pod=\"$pod\"}",
     "legendFormat": "Loaded"
    },
    {
     "expr": " jvm_classes_loaded_total{pod=\"$pod\"}",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "JVM GC Time [3m]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(jvm_gc_collection_seconds_sum{pod=\"$pod\"}[3m])",
     "legendFormat": "{{gc}}"
    }
   ]
  },
  {
   "title": "JVM GC Count Increase [3m]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(jvm_gc_collection_seconds_count{pod=\"$pod\"}[3m])",
     "legendFormat": "{{gc}}"
    }
   ]
  },
  {
   "title": "Tomcat Session Counter",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "tomcat_session_sessioncounter_total{pod=\"$pod\"}-tomcat_session_expiredsessions_total{pod=\"$pod\"}",
     "legendFormat": "Current"
    }
   ]
  },
  {
   "title": "Tomcat Thread Pool",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "tomcat_threadpool_connectioncount{protocol=\"http-nio\",pod=\"$pod\"}",
     "legendFormat": "Connection"
    },
    {
     "expr": "tomcat_threadpool_currentthreadcount{protocol=\"http-nio\",pod=\"$pod\"}",
     "legendFormat": "Current"
    },
    {
     "expr": "tomcat_threadpool_currentthreadsbusy{protocol=\"http-nio\",pod=\"$pod\"}",
     "legendFormat": "Busy"
    }
   ]
  },
  {
   "title": "Tomcat Servlet Request",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "tomcat_servlet_requestcount_total{pod=\"$pod\"}",
     "legendFormat": "{{servlet}}"
    }
   ]
  },
  {
   "title": "Tomcat Servlet Error",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "tomcat_servlet_errorcount_total{pod=\"$pod\"}",
     "legendFormat": "{{servlet}}"
    }
   ]
  }
 ]
}