def pomPath = "app/pom.xml"
def app = "tekion"
def repoFullName = "vinga2805/tekion"
def gitBranch = "master"
def registry = "${repoFullName}"
def registryCredential = 'docker_cred'
def dockerImage = ''
pipeline {
    agent any
    stages{
        stage('Build Jar'){
            steps {
                script {
                    def pomVersion = readMavenPom(file: "$pomPath").getVersion()
                    def version = "${pomVersion}"
                    def lastCommitHash = sh(returnStdout: true, script: "git log -n 1 --pretty=format:'%H'").trim()
                    def lastCommitAuthorEmail = sh(returnStdout: true, script: "git log -n 1 --pretty=format:'%ae'").trim()
                    if (pomVersion.endsWith("-SNAPSHOT")) {
                        echo "Snapshot version detected"
                        shortCommit = sh(returnStdout: true, script: "git log -n 1 --pretty=format:'%h'").trim()
                        gitBranch = gitBranch.substring(gitBranch.indexOf('/') + 1)
                        pomVersion = pomVersion.substring(0, pomVersion.indexOf('-'))
                        imageFullName = "${repoFullName}" + ":" + "snapshot_${pomVersion}_${gitBranch}_${shortCommit}"
                        artifactVersion = "${pomVersion}-snapshot.${gitBranch}.${shortCommit}"
                    } else {
                        echo "Proper release detected"
                        imageFullName = "${repoFullName}" + ":" + "${pomVersion}"
                        artifactVersion = "${pomVersion}"
                    }
                }
                sh "mvn clean package -f ${pomPath}"
            }

        }
        stage('Create image') {
            steps {
                script {
                    dockerImage = docker.build("${imageFullName}", "./app/")
                }
                
            }
        }
        stage('Publish artifacts'){
            steps {
                script {
                    docker.withRegistry( '', registryCredential ) {
                    dockerImage.push()
                    }              
                }
            }
        }
        stage('Cleaning images from Jenkins') {         
            steps {
                sh "docker rmi ${imageFullName}"
            }
        }
        stage ('Update Image tags in chart repository') {
            steps {
                script {
                    echo "----I AM Executing----"
                    sh """#!/bin/bash -x
                    pip install pyyaml
                    pip install pybump
                    python update_image.py ${imageFullName}                
                }            
            }       
        }
    }
}
